"""The common-mistakes page's citations, checked against the detectors they are exported from.

``frontend/src/lib/faultCitations.json`` is generated by ``src/pose/fault_citations.py`` and
committed, because the browser cannot read ``src/pose/movements``. A citation edited in a detector
without regenerating the file would leave the page naming a different paper than the studio shows
for the same detection; this is the test that says so.
"""

from __future__ import annotations

import json
import unittest

from src.pose.fault_citations import (
    MOVEMENTS_DIR, OUTPUT_JSON, all_citations, module_citations, registered_modules,
)
from tests.test_movement_mistakes_roster import REGISTERED, _authored_roster

REGENERATE = r".venv\Scripts\python.exe scripts/pose/export_fault_citations.py"


class ExportedFileTests(unittest.TestCase):
    def test_json_matches_the_detectors(self) -> None:
        # Compared as data, not bytes: autocrlf rewrites the file's line endings on checkout.
        exported = json.loads(OUTPUT_JSON.read_text(encoding="utf-8"))
        self.assertEqual(
            exported, all_citations(), f"faultCitations.json is stale; regenerate with {REGENERATE}"
        )

    def test_every_cited_fault_has_a_mistake_card(self) -> None:
        card_ids = {fault_id for entries in _authored_roster().values() for fault_id, _ in entries}
        self.assertLessEqual(set(all_citations()), card_ids)

    def test_every_mistake_card_cites_a_paper(self) -> None:
        # Holds today for all forty cards. A new rule that cites nothing renders without the
        # section, which is allowed -- but it should be a decision, so it fails here first.
        card_ids = {fault_id for entries in _authored_roster().values() for fault_id, _ in entries}
        self.assertEqual(card_ids - set(all_citations()), set())


class RegisteredScopeTests(unittest.TestCase):
    """Only registered movements reach the page, so only their citations are exported."""

    def test_the_registry_parse_names_exactly_the_registered_modules(self) -> None:
        self.assertEqual(registered_modules(), {module for _, module in REGISTERED})

    def test_an_unregistered_live_rule_is_not_exported(self) -> None:
        """Jumping Jacks has a live, cited rule since 2026-09-26 and no registration. The source
        DOES carry the citation (the companion assertion), and the export must still omit it:
        the page has no Jumping Jacks card to hang it on."""
        source = (MOVEMENTS_DIR / "jumping_jacks.py").read_text(encoding="utf-8")
        self.assertIn("jj_incomplete_leg_rom", module_citations(source))
        self.assertNotIn("jj_incomplete_leg_rom", all_citations())


class ModuleCitationsTests(unittest.TestCase):
    def test_reads_literals_constants_and_implicit_concatenation(self) -> None:
        source = (
            'PAPER = "Ford (2015)."\n'
            "def a():\n"
            '    build_detection(fault_id="x", citation="Zellmer " "(2019).")\n'
            "def b():\n"
            '    build_detection(fault_id="y", citation=PAPER)\n'
        )
        self.assertEqual(module_citations(source), {"x": "Zellmer (2019).", "y": "Ford (2015)."})

    def test_a_rule_citing_nothing_is_left_out(self) -> None:
        source = (
            'build_detection(fault_id="x")\n'
            'build_detection(fault_id="y", citation="")\n'
        )
        self.assertEqual(module_citations(source), {})

    def test_the_same_paper_at_two_call_sites_is_one_entry(self) -> None:
        source = (
            'build_detection(fault_id="x", citation="P.")\n'
            'build_detection(fault_id="x", citation="P.")\n'
        )
        self.assertEqual(module_citations(source), {"x": "P."})

    def test_two_papers_for_one_fault_raise(self) -> None:
        source = (
            'build_detection(fault_id="x", citation="P.")\n'
            'build_detection(fault_id="x", citation="Q.")\n'
        )
        with self.assertRaisesRegex(ValueError, "two different papers"):
            module_citations(source)

    def test_an_unreadable_citation_raises_instead_of_vanishing(self) -> None:
        source = 'build_detection(fault_id="x", citation=f"{year}")\n'
        with self.assertRaisesRegex(ValueError, "not a string literal"):
            module_citations(source, "m.py")
