import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import { avgKneeAngle, type SignalLandmark } from "../lib/repSignal";

// Ground truth generated by scripts/pose/capture_rep_signal_golden.py from a REAL clip. The shared
// segmentation fixture pins signal->windows; this pins landmarks->signal, and nothing else does.
//
// NOT `new URL("../../../tests/...", import.meta.url)` — Vite 6's asset plugin statically rewrites
// that form into an http://.../@fs/... URL, which readFileSync rejects. Resolve from the test
// file's own directory instead, so the path stays independent of where vitest was launched from.
// (Same reason and same shape as lib.repSegmentation.test.ts.)
const FIXTURE = resolve(
  dirname(fileURLToPath(import.meta.url)), "../../../tests/fixtures/rep_signal_golden.json"
);
const golden = JSON.parse(readFileSync(FIXTURE, "utf-8")) as {
  source: string;
  cases: { landmarks: SignalLandmark[] | null; avg_knee_angle: number | null }[];
};

// Python's numeric path is float32 end to end (geometry.py:28 landmarks_to_array, :49
// visible_point, :109 mean_finite), while JS numbers are float64. On this fixture the largest
// observed float32-vs-float64 drift is ~1.45e-5 degrees (frame 28) -- consistent with float32
// epsilon (1.19e-7) at angle magnitudes of ~100 degrees. A real port divergence (2-D instead of
// 3-D, a different visibility gate, the historical NaN-z collapse) is degrees or a NaN/number
// mismatch, not a fraction of a thousandth of a degree, so this constant has ~4 orders of
// magnitude of headroom below any real bug while comfortably clearing dtype noise.
const FLOAT32_TOLERANCE_DEGREES = 1e-4;

describe("avgKneeAngle matches Python on real landmarks", () => {
  it("has a golden file with measurable frames in it", () => {
    expect(golden.cases.length).toBeGreaterThan(0);
    expect(golden.cases.some((c) => c.avg_knee_angle !== null)).toBe(true);
  });

  it("agrees within float32-vs-float64 precision on every frame", () => {
    for (const [i, testCase] of golden.cases.entries()) {
      const got = avgKneeAngle(testCase.landmarks);
      if (testCase.avg_knee_angle === null) {
        expect(Number.isNaN(got), `frame ${i} should be unmeasurable`).toBe(true);
      } else {
        // Measured max on this fixture is ~1.45e-5 (frame 28); see notes/rep_segmentation_sp2_measurements.md.
        expect(Math.abs(got - testCase.avg_knee_angle), `frame ${i}`).toBeLessThan(
          FLOAT32_TOLERANCE_DEGREES
        );
      }
    }
  });
});
